### ISSUE TITLE
ERROR: ChatCompletion Failed

### ISSUE THREAD

**Issue by Rolocker** [ian-kent/gptchat#1]
Hello,

Apologies if there's a simple solution, I'm not to familiar with how to do this. I've copied the repository onto my computer, installed go, and then attempted to run from gptchat-main and received the following error:

ERROR: _ChatCompletion failed: error, status code: 401, message: You didn't provide an API key. You need to provide your API key in an Authorization header using Bearer auth (i.e. Authorization: Bearer YOUR_KEY), or as the password field (with blank username) if you're accessing the API from your browser and are prompted for a username and password. You can obtain an API key from https://platform.openai.com/account/api-keys._

I attempted to input "Y Authorization: _my api key_" and it asked me for "USER:", but nothing I could think of worked including email, username, blank, or my api key. I've also modified main.go to already use my api key. Edit: Forgot to mention I also tried typing the "I'd like to tell you a story." prompt like in the videos but only got the same error.

Do you know how I can get past this error?

**Comment by Illumibatchi** [comment]
I am having the same issue!

**Comment by Marcus-Arcadius** [comment]
got the same error, still figuring out how to input api key

**Comment by NCatalani** [comment]
Have you exported the enviroment variable OPENAI_API_KEY with your gpt4 key?

@ian-kent I think it's best to update the README to be more clear

**Comment by Marcus-Arcadius** [comment]
> Have you exported the enviroment variable OPENAI_API_KEY with your gpt4 key?
> 
> @ian-kent I think it's best to update the README to be more clear

Could you clarify this please?

**Comment by NCatalani** [comment]
If you're on a UNIX-based system is as simple as hoping into a terminal and running:

```bash

export OPENAI_API_KEY="YOUR_API_KEY_GOES_HERE"
```

Remember to add to your ~/.bashrc (or equivalent) in order to persist into other terminal sessions.

**Comment by Marcus-Arcadius** [comment]
> If you're on a UNIX-based system is as simple as hoping into a terminal and running:
> 
> ```shell
> export OPENAI_API_KEY="YOUR_API_KEY_GOES_HERE"
> ```
> 
> Remember to add to your ~/.bashrc (or equivalent) in order to persist into other terminal sessions.

Cheers mate this worked, I'm on windows is there a way to make it persist into other terminal sessions?

**Comment by NCatalani** [comment]
> > If you're on a UNIX-based system is as simple as hoping into a terminal and running:
> > ```shell
> > export OPENAI_API_KEY="YOUR_API_KEY_GOES_HERE"
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Remember to add to your ~/.bashrc (or equivalent) in order to persist into other terminal sessions.
> 
> Cheers mate this worked, I'm on windows is there a way to make it persist into other terminal sessions?

From cmd.exe

```bash
setx OPENAI_API_KEY YOUR_API_KEY /m
```

Or powershell

```powershell
[System.Environment]::SetEnvironmentVariable('OPENAI_API_KEY','YOUR_API_KEY',[System.EnvironmentVariableTarget]::User)

**Comment by Explorergt92** [comment]
On my personal win 11 pro machine I right click the start menu and go to settings. Type "enviro" in the search box and select "Edit the system environment variables" option , then click "Environment Variables...", next click the "New..." button under the "System variables" box under the lower window... Enter OPENAI_API_KEY for the "Variable name" and your API key for the value. and click ok. Now you'll be using that API key for anything you run that uses "(os.Getenv("OPENAI_API_KEY")" or "OPENAI_API_KEY = os.getenv("OPENAI_API_KEY")"

**Comment by ian-kent** [comment]
I've updated the readme to mention setting the API key, and I've updated the app to prompt for the API key on startup if it isn't set. Hopefully this should simplify things a bit!
