### ISSUE TITLE
Cannot find plugin directory

### ISSUE THREAD

**Issue by ngivan2004** [ian-kent/gptchat#2]
Hi. I am getting the following error after building and running the executable.

FYI I am on MacOS

`error loading compiled plugins: error loading compiled plugins: open ./module/plugin/compiled/: no such file or directory`

**Comment by ian-kent** [comment]
What steps are you taking to run it? 🤔 

If you're running it from the `gptchat` directory then it should be able to find the `compiled` directory, from anywhere else it wouldn't work.

I'll see if I can make it a bit more resilient though so it doesn't just fail on startup.

**Comment by ian-kent** [comment]
Closing this as I've updated the code to do some checks on startup, even if that doesn't solve the issue it should help diagnose it.
