### ISSUE TITLE
-buildmode=plugin not supported on windows/amd64

### ISSUE THREAD

**Issue by Zinnusl** [ian-kent/gptchat#4]
See title. I don't expect a bug fix I guess, but I'll leave it here so people can see that using Windows probably will not work 100%. I ended up using WSL instead.

Edit: I installed golang via scoop, maybe there is a version that does support this?

**Comment by ian-kent** [comment]
> maybe there is a version that does support this

The docs at https://pkg.go.dev/plugin say
> Plugins are currently supported only on Linux, FreeBSD, and macOS, making them unsuitable for applications intended to be portable.

so I wouldn't expect any other versions to support it 😞
