### ISSUE TITLE
Can this be modified to work with GPT-3?

### ISSUE THREAD

**Issue by jsonsmth** [ian-kent/gptchat#7]
For those waiting for GPT-4 API access, can this be modded to work with GPT-3? Thanks!

**Comment by ian-kent** [comment]
I don't think so. GPT-3/3.5 struggles with the tools, coding and hallucinates a lot.

There's a [reddit thread here](https://www.reddit.com/r/ChatGPT/comments/12a0ajb/comment/jeqnwn4/) where someone tried it and it didn't work very well.

I think you'll have to wait for GPT-4 unfortunately.
